/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nox;

import java.awt.Color;
import java.sql.*;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import demo.Main;

/**
 *
 * @author Vam
 */
public class Ccategory extends javax.swing.JFrame {
    private Main application;
    /**
     * Creates new form Profile_1
     */
    int x;
    /*DatabaseConnection con_16 = new DatabaseConnection();
    Statement s;
    ResultSet rs;*/
    public Ccategory() throws SQLException, ClassNotFoundException {   
     // NOI18N

// Code adding the component to the parent container - not shown here
 initComponents();
                Connection c;
                Statement stmt,st;
                ResultSet rs,rs1;
                Class.forName("com.mysql.jdbc.Driver");
                c = DriverManager.getConnection ("jdbc:mysql://localhost:3306/dataa", "root", "freak");        
                stmt = c.createStatement();
                String sql;
                sql="truncate table total";
                String y="0";
                int rss = stmt.executeUpdate(sql);
                sql = "insert into total values('"+y+"')";
                rss = stmt.executeUpdate(sql);
                sql="truncate table total2";
                rss = stmt.executeUpdate(sql);
                sql = "insert into total2 values('"+y+"')";
                rss = stmt.executeUpdate(sql);
                sql="truncate table total3";
                rss = stmt.executeUpdate(sql);
                sql = "insert into total3 values('"+y+"')";
                rss = stmt.executeUpdate(sql);
                sql="truncate table total4";
                rss = stmt.executeUpdate(sql);
                sql = "insert into total4 values('"+y+"')";
                rss = stmt.executeUpdate(sql);
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        Transactions_Label = new javax.swing.JLabel();
        BookTickets_Label = new javax.swing.JLabel();
        Logout_Label = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Logout_Label1 = new javax.swing.JLabel();
        Logout_Label2 = new javax.swing.JLabel();
        Logout_Label3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setOpaque(false);

        Transactions_Label.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        Transactions_Label.setForeground(new java.awt.Color(255, 255, 255));
        Transactions_Label.setText("About Us");
        Transactions_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Transactions_LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Transactions_LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Transactions_LabelMouseExited(evt);
            }
        });

        BookTickets_Label.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        BookTickets_Label.setForeground(new java.awt.Color(255, 255, 255));
        BookTickets_Label.setText("GotoCart >>>");
        BookTickets_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookTickets_LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BookTickets_LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BookTickets_LabelMouseExited(evt);
            }
        });

        Logout_Label.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        Logout_Label.setForeground(new java.awt.Color(255, 255, 255));
        Logout_Label.setText("Back to Main >>");
        Logout_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Logout_LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Logout_LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Logout_LabelMouseExited(evt);
            }
        });

        jLabel2.setText("jLabel2");
        jLabel2.setMaximumSize(new java.awt.Dimension(320, 240));
        jLabel2.setMinimumSize(new java.awt.Dimension(320, 240));
        jLabel2.setPreferredSize(new java.awt.Dimension(320, 240));

        jLabel3.setText("jLabel2");
        jLabel3.setMaximumSize(new java.awt.Dimension(240, 320));
        jLabel3.setMinimumSize(new java.awt.Dimension(240, 320));
        jLabel3.setName(""); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(240, 320));

        jLabel4.setText("jLabel2");
        jLabel4.setMaximumSize(new java.awt.Dimension(240, 320));
        jLabel4.setMinimumSize(new java.awt.Dimension(240, 320));
        jLabel4.setPreferredSize(new java.awt.Dimension(240, 320));

        Logout_Label1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        Logout_Label1.setForeground(new java.awt.Color(255, 255, 255));
        Logout_Label1.setText("See inside >>>");
        Logout_Label1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Logout_Label1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Logout_Label1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Logout_Label1MouseExited(evt);
            }
        });

        Logout_Label2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        Logout_Label2.setForeground(new java.awt.Color(255, 255, 255));
        Logout_Label2.setText("See inside >>>");
        Logout_Label2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Logout_Label2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Logout_Label2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Logout_Label2MouseExited(evt);
            }
        });

        Logout_Label3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        Logout_Label3.setForeground(new java.awt.Color(255, 255, 255));
        Logout_Label3.setText("See inside >>>");
        Logout_Label3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Logout_Label3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Logout_Label3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Logout_Label3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(346, 346, 346)
                .addComponent(Transactions_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(BookTickets_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(Logout_Label)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(Logout_Label1)
                        .addGap(175, 175, 175)
                        .addComponent(Logout_Label2)
                        .addGap(166, 166, 166)
                        .addComponent(Logout_Label3)))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Transactions_Label)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BookTickets_Label)
                        .addComponent(Logout_Label)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Logout_Label1)
                    .addComponent(Logout_Label2)
                    .addComponent(Logout_Label3))
                .addContainerGap(144, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel1, gridBagConstraints);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nox/cinemas/Background/background.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jLabel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Logout_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout_LabelMouseExited
        Logout_Label.setForeground(Color.WHITE);
    }//GEN-LAST:event_Logout_LabelMouseExited

    private void Logout_LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout_LabelMouseEntered
        Logout_Label.setForeground(Color.ORANGE);
    }//GEN-LAST:event_Logout_LabelMouseEntered

    private void Logout_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout_LabelMouseClicked
        try {
            //  new Login().setVisible(true);
            Connection c;
            Statement stmt,st;
            ResultSet rs,rs1;
            Class.forName("com.mysql.jdbc.Driver");
                c = DriverManager.getConnection ("jdbc:mysql://localhost:3306/dataa", "root", "freak");
                stmt = c.createStatement();
            String sql;
            sql="truncate table cart";
            int rss = stmt.executeUpdate(sql);
  
            rss = stmt.executeUpdate(sql);
            } catch (SQLException ex) {
                Logger.getLogger(Ccategory.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
            Logger.getLogger(Ccategory.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            dispose();
    }//GEN-LAST:event_Logout_LabelMouseClicked

    private void BookTickets_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookTickets_LabelMouseExited
        BookTickets_Label.setForeground(Color.WHITE);
    }//GEN-LAST:event_BookTickets_LabelMouseExited

    private void BookTickets_LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookTickets_LabelMouseEntered
        BookTickets_Label.setForeground(Color.ORANGE);
    }//GEN-LAST:event_BookTickets_LabelMouseEntered

    private void BookTickets_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookTickets_LabelMouseClicked

            try {
                // new Book_Tickets().setVisible(true);
                new Cartcat().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(Ccategory.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Ccategory.class.getName()).log(Level.SEVERE, null, ex);
            }
            dispose();
    }//GEN-LAST:event_BookTickets_LabelMouseClicked

    private void Transactions_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Transactions_LabelMouseClicked
        // TODO add your handling code here:
    //    new About_us().setVisible(true);
        dispose();
    }//GEN-LAST:event_Transactions_LabelMouseClicked

    private void Transactions_LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Transactions_LabelMouseEntered
        // TODO add your handling code here:
        Transactions_Label.setForeground(Color.ORANGE);
    }//GEN-LAST:event_Transactions_LabelMouseEntered

    private void Transactions_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Transactions_LabelMouseExited
        Transactions_Label.setForeground(Color.WHITE);
    }//GEN-LAST:event_Transactions_LabelMouseExited

    private void Logout_Label1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout_Label1MouseClicked
        // TODO add your handling code here:
                try {
                    //System.out.println(y);
                    new Mobilecat().setVisible(true);
                    
                } catch (SQLException ex) {
                    Logger.getLogger(Mobilecat.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Mobilecat.class.getName()).log(Level.SEVERE, null, ex);
                }
        dispose();
    }//GEN-LAST:event_Logout_Label1MouseClicked

    private void Logout_Label1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout_Label1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Logout_Label1MouseEntered

    private void Logout_Label1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout_Label1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Logout_Label1MouseExited

    private void Logout_Label2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout_Label2MouseClicked
        // TODO add your handling code here:
                try {
                    //System.out.println(y);
                    new Computercat().setVisible(true);
                    
                } catch (SQLException ex) {
                    Logger.getLogger(Mobilecat.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Mobilecat.class.getName()).log(Level.SEVERE, null, ex);
                }
        dispose();
        
        
    }//GEN-LAST:event_Logout_Label2MouseClicked

    private void Logout_Label2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout_Label2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Logout_Label2MouseEntered

    private void Logout_Label2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout_Label2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Logout_Label2MouseExited

    private void Logout_Label3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout_Label3MouseClicked
        // TODO add your handling code here:
                try {
                    //System.out.println(y);
                    new Cameracat().setVisible(true);
                    
                } catch (SQLException ex) {
                    Logger.getLogger(Mobilecat.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Mobilecat.class.getName()).log(Level.SEVERE, null, ex);
                }
        dispose();
    }//GEN-LAST:event_Logout_Label3MouseClicked

    private void Logout_Label3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout_Label3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Logout_Label3MouseEntered

    private void Logout_Label3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout_Label3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Logout_Label3MouseExited
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ccategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ccategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ccategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ccategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Ccategory().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Ccategory.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Ccategory.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BookTickets_Label;
    private javax.swing.JLabel Logout_Label;
    private javax.swing.JLabel Logout_Label1;
    private javax.swing.JLabel Logout_Label2;
    private javax.swing.JLabel Logout_Label3;
    private javax.swing.JLabel Transactions_Label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
