/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nox;

import java.awt.Color;
import java.sql.*;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Vam
 */
public class desc extends javax.swing.JFrame {

    /**
     * Creates new form Profile_1
     */
    int y,x;
    String b,sql;
    
    //DatabaseConnection con_16 = new DatabaseConnection();
    Statement s;
    ResultSet rs;
    public desc() throws SQLException, ClassNotFoundException {   
     // NOI18N

// Code adding the component to the parent container - not shown here
       
            
    }
    public void get_data(String x1,String x2) throws ClassNotFoundException, SQLException {
        this.b = x1;
        this.sql = x2;
        System.out.println("yes"+b);
            System.out.println(sql);
            call();
    }
    public void call() throws ClassNotFoundException, SQLException{
         initComponents();
        System.out.println(b);
        System.out.println(sql);
            Connection c;
                Statement stmt,st;
                ResultSet rs,rs1;
                Class.forName("com.mysql.jdbc.Driver");
                c = DriverManager.getConnection ("jdbc:mysql://localhost:3306/dataa", "root", "freak");        
                stmt = c.createStatement();
                int rss = stmt.executeUpdate(sql);
               jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(b))); // NOI18N
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        Transactions_Label = new javax.swing.JLabel();
        BookTickets_Label = new javax.swing.JLabel();
        Logout_Label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(940, 420));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setOpaque(false);

        Transactions_Label.setBackground(new java.awt.Color(51, 51, 51));
        Transactions_Label.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        Transactions_Label.setForeground(new java.awt.Color(51, 51, 51));
        Transactions_Label.setText("About Us");
        Transactions_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Transactions_LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Transactions_LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Transactions_LabelMouseExited(evt);
            }
        });

        BookTickets_Label.setBackground(new java.awt.Color(51, 51, 51));
        BookTickets_Label.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        BookTickets_Label.setForeground(new java.awt.Color(51, 51, 51));
        BookTickets_Label.setText("Add to Cart");
        BookTickets_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookTickets_LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BookTickets_LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BookTickets_LabelMouseExited(evt);
            }
        });

        Logout_Label.setBackground(new java.awt.Color(102, 102, 102));
        Logout_Label.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        Logout_Label.setForeground(new java.awt.Color(51, 51, 51));
        Logout_Label.setText("Back to Categories");
        Logout_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Logout_LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Logout_LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Logout_LabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(Transactions_Label)
                .addGap(56, 56, 56)
                .addComponent(BookTickets_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Logout_Label)
                .addGap(0, 611, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Transactions_Label)
                    .addComponent(BookTickets_Label)
                    .addComponent(Logout_Label))
                .addContainerGap(648, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel1, gridBagConstraints);

        jLabel1.setMaximumSize(new java.awt.Dimension(940, 420));
        jLabel1.setMinimumSize(new java.awt.Dimension(940, 420));
        jLabel1.setPreferredSize(new java.awt.Dimension(940, 420));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jLabel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Logout_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout_LabelMouseExited
        Logout_Label.setForeground(Color.WHITE);
    }//GEN-LAST:event_Logout_LabelMouseExited

    private void Logout_LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout_LabelMouseEntered
        Logout_Label.setForeground(Color.ORANGE);
    }//GEN-LAST:event_Logout_LabelMouseEntered

    private void Logout_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout_LabelMouseClicked
      //  new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_Logout_LabelMouseClicked

    private void BookTickets_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookTickets_LabelMouseExited
        BookTickets_Label.setForeground(Color.WHITE);
    }//GEN-LAST:event_BookTickets_LabelMouseExited

    private void BookTickets_LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookTickets_LabelMouseEntered
        BookTickets_Label.setForeground(Color.ORANGE);
    }//GEN-LAST:event_BookTickets_LabelMouseEntered

    private void BookTickets_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookTickets_LabelMouseClicked
        // new Book_Tickets().setVisible(true);
       // dispose();
    }//GEN-LAST:event_BookTickets_LabelMouseClicked

    private void Transactions_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Transactions_LabelMouseClicked
        // TODO add your handling code here:
        //    new About_us().setVisible(true);
        dispose();
    }//GEN-LAST:event_Transactions_LabelMouseClicked

    private void Transactions_LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Transactions_LabelMouseEntered
        // TODO add your handling code here:
        Transactions_Label.setForeground(Color.ORANGE);
    }//GEN-LAST:event_Transactions_LabelMouseEntered

    private void Transactions_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Transactions_LabelMouseExited
        Transactions_Label.setForeground(Color.WHITE);
    }//GEN-LAST:event_Transactions_LabelMouseExited
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(desc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(desc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(desc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(desc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                try {
                    new desc().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(desc.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(desc.class.getName()).log(Level.SEVERE, null, ex);
                }
               
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BookTickets_Label;
    private javax.swing.JLabel Logout_Label;
    private javax.swing.JLabel Transactions_Label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
